fork: true
repo_slug: vszakats/harbour-core
site_slug: vszakats/harbour-core
site_branch_and_root: master/docs/
dl_url: https://github.com/vszakats/harbour-core/releases
short_version: "3.4"
full_version: "3.4.0dev"
license_file: LICENSE.txt

example_categories:
  - basic
  - arrays
  - database
  - extensions
  - web
collections:
  example:
    output: true
defaults:
  - scope:
      path: ""
      type: example
    values:
      layout: example

incremental: true
sass:
  style: compressed
